---
version: "3.7"
services:
  # container name
  dev:

    # image that can be pulled
    image: arecarn/c-and-cpp

    # keep stdin open even if not attached
    # TODO determine if this is necessary
    stdin_open: true

    # allocate a pseudo-tty
    tty: true

    # build Dockerfile in the same directory as this file
    build: .

    # mount the current directory inside the container
    volumes:
      - ${PWD}:${PWD}
      - "${XAUTHORITY:-~/.Xauthority}:/home/${USER}/.Xauthority" # x11 forwarding

    # when entering the container stay in the current directory
    working_dir: ${PWD}

    # container environment variables
    environment:
      - DISPLAY=${DISPLAY} # for X11 forwarding
      - UID=${UID_VALUE:? Error -> UID_VALUE must be set and exported.}
      - GID=${GID_VALUE:? Error -> GID_VALUE must be set and exported}
      - USER=${USER:? Error -> USER must be set and exported}

    # start a bash session
    command: /bin/bash

    entrypoint: ${PWD}/docker_entrypoint.sh
